version: '3.8'

services:
  # PostgreSQL Database (optional - comment out to use SQLite)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: news_sentiment
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend + Frontend
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Use PostgreSQL (uncomment these and comment DATABASE_URL below)
      # DATABASE_URL: postgresql://newsuser:newspass@db:5432/news_sentiment

      # Use SQLite (default)
      DATABASE_URL: sqlite:////app/data/news_sentiment.db

      SECRET_KEY: ${SECRET_KEY:-dev-secret-key}
      FLASK_ENV: ${FLASK_ENV:-development}
      PORT: 5000
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    depends_on:
      - db
    restart: unless-stopped

  # Frontend Development Server (optional - for development only)
  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    profiles:
      - dev

volumes:
  postgres_data:
